### PR TITLE
Changed default_auto_field to "django.db.models.BigAutoField" - Support more than 2**31 records in all models

### PR DESCRIPTION
**Pull request by uri-rodberg**
AppConfig: Changed default_auto_field to "django.db.models.BigAutoField" + added migrations.

(Support more than 2**31 records in all models).

### CODE REVIEW

**Comment by uri-rodberg** [comment]
This is a major change and I recommend raising the version number accordingly (at least to 1.10 or something).

**Review by jefftriplett — APPROVED** [review]
🎉

**Comment by uri-rodberg** [comment]
I thought about it and the change to `friendship/apps.py` might be ignored by Django <= 3.1, and then I added a new migration. So it might be that this change will not be fully supported by Django <= 3.1. I guess if running `makemigrations` on these versions of Django might revert the migration added by this pull request. So maybe it would require Django version to be at least 3.2.

**Comment by uri-rodberg** [comment]
Hi,

According to https://www.djangoproject.com/download/, only Django versions >= 3.2 are supported right now. So you can consider accepting this pull request now while specifying the minimal Django version supported to 3.2.

**Comment by jefftriplett** [comment]
I rebased your branch on #182 and reached out to a few friends about the <3.2 support. Will follow up after I hear back. We are overdue for the 4.1 (soon 4.2) trove release and then dropping 3.6. 🔜

**Comment by jefftriplett** [comment]
@uri-rodberg thank you!

**Pull request merged**
