### PR TITLE
Fixed issue https://github.com/revsys/django-friendship/issues/86 + reformat code.

### PR DESCRIPTION
**Pull request by uri-rodberg**
+ Fixed issue & tests.

### CODE REVIEW

**Comment by uri-rodberg** [comment]
+ Fixed tests.

**Comment by frankwiles** [comment]
Appreciate the work on this and apologies that we didn't get to it sooner, but I just ran Black over the whole codebase and refactored the method before I saw this PR sadly.

**Comment by uri-rodberg** [comment]
> Appreciate the work on this and apologies that we didn't get to it sooner, but I just ran Black over the whole codebase and refactored the method before I saw this PR sadly.

You ignored all this pull request and didn't fix other issues such as `def create_user(self, username, email_address, password)`.

-1

**Comment by fcurella** [comment]
@uri-rodberg that’s not how it works.

Your PR was merged in about a month, which is IMHO is a totally acceptable time frame in open source.

I don’t know why you think you can demand first-class support for a software you’re not paying for.

**Pull request closed without merging**
