### PR TITLE
Blocking functionality

### PR DESCRIPTION
**Pull request by tjcrowley**
Expanding on the original follower and friend models, added a Block model and associated methods and managers to enable django-friendships to maintain a blocklist for each user of users they do not want to see or be seen by. 

From the documentation:

Getting Data about Blocks
* List of a user's blockers: ``Block.objects.blockers(request.user)``
* List of who a user is blocking: ``Block.objects.blocking(request.user)``
* Test if a user is blocked: ``Block.objects.is_blocked(request.user, other_user) == True``

Read the addition to the docs and let me know if it's lacking in any way. Added my name to the author list as well. 

D.

### CODE REVIEW

**Comment by tjcrowley** [comment]
I have tried to debug this but it's failing saying it can't find the table. Please advise?

**Comment by tjcrowley** [comment]
I'll see what I can do about this over the weekend.

**Comment by babus** [comment]
Any chance for this to be released soon? Thanks for the work!

**Comment by frankwiles** [comment]
Just released v1.6.0 with this merge and another feature.  Thanks!

**Pull request merged**
